import { request } from './client.js';

export const login = (email, password) => request('/auth/login', { method: 'POST', body: { email, password } });
export const me = () => request('/auth/me');
export const getLookups = () => request('/lookups');
export const getSettings = () => request('/lookups/settings');
export const createCustomer = (body) => request('/lookups/customers', { method: 'POST', body });
export const createMarketingSource = (body) => request('/lookups/marketing-sources', { method: 'POST', body });
export const createEstimateType = (body) => request('/lookups/estimate-types', { method: 'POST', body });
export const createInstaller = (body) => request('/lookups/installers', { method: 'POST', body });
export const createListItem = (list, body) => request('/lookups/lists/' + list, { method: 'POST', body });
export const patchListItem = (list, id, body) => request('/lookups/lists/' + list + '/' + id, { method: 'PATCH', body });
export const listEstimates = (filters) => request('/estimates', { params: filters });
export const getEstimate = (id) => request('/estimates/' + id);
export const createEstimate = (body) => request('/estimates', { method: 'POST', body });
export const updateEstimate = (id, body) => request('/estimates/' + id, { method: 'PATCH', body });
export const convertEstimate = (id, body = {}) => request('/estimates/' + id + '/convert', { method: 'POST', body });
export const getJob = (id) => request('/estimates/' + id + '/job');
export const updateJob = (id, body) => request('/estimates/' + id + '/job', { method: 'PATCH', body });
export const addJobItem = (id, kind, body) => request('/estimates/' + id + '/job/' + kind, { method: 'POST', body });
export const updateJobItem = (id, kind, itemId, body) => request('/estimates/' + id + '/job/' + kind + '/' + itemId, { method: 'PATCH', body });
export const removeJobItem = (id, kind, itemId) => request('/estimates/' + id + '/job/' + kind + '/' + itemId, { method: 'DELETE' });
export const confirmPayment = (id, itemId, body) => request('/estimates/' + id + '/job/payments/' + itemId + '/confirm', { method: 'POST', body });
